services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    working_dir: /app/backend
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
    volumes:
      - ./backend:/app/backend:delegated
    ports:
      - "8000:8000"
    command: poetry run uvicorn api:app --host 0.0.0.0 --port 8000 --reload
