services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build:
      # Build from repo root so the vendored `legogpt/` package is included
      context: .
      dockerfile: backend/Dockerfile.dev
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend:delegated
    ports:
      - "8000:8000"
    command: lego-gpt-server
  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend:delegated
    command: lego-gpt-worker
  detector:
    build:
      context: .
      dockerfile: detector/Dockerfile.dev
    working_dir: /app
    volumes:
      - ./backend:/app/backend:delegated
      - ./detector:/app/detector:delegated
    command: lego-detect-worker
