services:
  api:
    build:
      # Build from repo root so the vendored `legogpt/` package is included
      context: .
      dockerfile: backend/Dockerfile.dev
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend:delegated
    ports:
      - "8000:8000"
    command: python server.py
  detector:
    build:
      context: .
      dockerfile: detector/Dockerfile.dev
    working_dir: /app
    volumes:
      - ./backend:/app/backend:delegated
      - ./detector:/app/detector:delegated
    command: python -m detector.worker
