services:
  api:
    build:
      # Build from repo root so the vendored `legogpt/` package is included
      context: .
      dockerfile: backend/Dockerfile.dev
    working_dir: /app/backend
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
    volumes:
      - ./backend:/app/backend:delegated
    ports:
      - "8000:8000"
    command: poetry run uvicorn api:app --host 0.0.0.0 --port 8000 --reload
