# MkDocs configuration for the archived documentation site
site_name: Lego GPT Docs
site_url: https://example.com
docs_dir: docs
site_dir: site
nav:
  - Home: index.md
  - Architecture: ARCHITECTURE.md
  - Maintenance: COMMUNITY_MAINTENANCE.md
  - Dependency Versions: DEPENDENCY_VERSIONS.md
  - Backlog: PROJECT_BACKLOG.md
