# MkDocs configuration for the archived documentation site
site_name: Lego GPT Docs
site_url: https://example.com
docs_dir: docs
site_dir: site
nav:
  - Home: index.md
  - Architecture: ARCHITECTURE.md
  - Maintenance: COMMUNITY_MAINTENANCE.md
  - Issue Triage: ISSUE_TRIAGE_GUIDE.md
  - LTS Policy: LTS_POLICY.md
  - Dependency Versions: DEPENDENCY_VERSIONS.md
  - Render Deployment: RENDER_DEPLOYMENT.md
  - Backlog: PROJECT_BACKLOG.md
