# render.yaml  ── Blueprint: API + Redis + Static Site
services:
  # ────────────────────────────────────────────────
  - type: web
    name: lego-gpt-api
    env: docker
    dockerfilePath: backend/Dockerfile.cpu
    autoDeploy: true
    branch: main
    plan: standard            # 2 GB RAM / 1 vCPU
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: lego-gpt-redis
          property: connectionString
      - key: JWT_SECRET        # consider blanking this and setting via dashboard
        sync: false
        value: ycQGGSqO3/JYGY96TLnC829sXFPHMW+OFIcx/OSL+gs=
      - key: RATE_LIMIT
        value: "10"
      - key: CORS_ORIGINS
        value: "http://localhost:5173,https://lego-gpt.onrender.com"

  # ────────────────────────────────────────────────
  - type: redis
    name: lego-gpt-redis
    tier: free
    maxmemoryPolicy: allkeys-lru

  # ────────────────────────────────────────────────
  - type: static
    name: lego-gpt                 # → https://lego-gpt.onrender.com
    rootDir: frontend              # React app lives here
    buildCommand: |
      pnpm install --frozen-lockfile
      pnpm run build
    staticPublishPath: dist        # Vite output folder
    branch: main
    autoDeploy: true
