# render.yaml  ── Blueprint: API + Redis + Static Site
services:
  # ────────────────────────────────────────────────
  - type: web
    name: lego-gpt-api
    env: docker
    dockerfilePath: backend/Dockerfile.cpu
    autoDeploy: true
    branch: main
    plan: standard            # 2 GB RAM / 1 vCPU
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: lego-gpt-redis
          property: connectionString
      - key: JWT_SECRET        # consider blanking and setting via dashboard
        sync: false
        value: ycQGGSqO3/JYGY96TLnC829sXFPHMW+OFIcx/OSL+gs=
      - key: RATE_LIMIT
        value: "10"
      - key: CORS_ORIGINS
        value: "http://localhost:5173,https://lego-gpt.onrender.com"

  # ────────────────────────────────────────────────
  - type: redis
    name: lego-gpt-redis
    plan: free                # Hobby plan – sleeps when idle
    ipAllowList:
      - source: 0.0.0.0/0
    maxmemoryPolicy: allkeys-lru

  # ────────────────────────────────────────────────
  - type: web                 # static sites are “web” with runtime: static
    name: lego-gpt            # → https://lego-gpt.onrender.com
    runtime: static
    rootDir: frontend
    buildCommand: |
      pnpm install --frozen-lockfile
      pnpm run build
    staticPublishPath: dist
    branch: main
    autoDeploy: true
