# render.yaml  ── one Blueprint, two services
services:
  # ────────────────────────────────────────────────
  - type: web
    name: lego-gpt-api
    env: docker
    dockerfilePath: backend/Dockerfile.cpu   # ← the one we inspected
    autoDeploy: true
    branch: main
    plan: standard          # 2 GB RAM / 1 vCPU   $25 mo
    envVars:
      # Inject Redis URL from the service defined below
      - key: REDIS_URL
        fromService:
          type: redis
          name: lego-gpt-redis
          property: connectionString
      # Your auth secret – leave empty in Git, set in the Render UI
      - key: JWT_SECRET
        sync: false
        value: ycQGGSqO3/JYGY96TLnC829sXFPHMW+OFIcx/OSL+gs=
      # Per-user request cap
      - key: RATE_LIMIT
        value: "10"
      # Allowed browser origins (local dev + Render static site)
      - key: CORS_ORIGINS
        value: "http://localhost:5173,https://lego-gpt.onrender.com"

  # ────────────────────────────────────────────────
  - type: redis
    name: lego-gpt-redis
    plan: free        # Hobby plan – sleeps when idle
    maxmemoryPolicy: allkeys-lru
