# render.yaml -- Blueprint: API + Redis + Static Site
services:
  - type: web
    name: lego-gpt-api-green
    runtime: python
    rootDir: .
    buildCommand: pip install -e backend
    startCommand: uvicorn backend.api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: REDIS_URL
        fromService:
          type: redis
          name: lego-gpt-redis
          property: connectionString
      - key: JWT_SECRET
        value: ycQGGSqO3/JYGY96TLnC829sXFPHMW+OFIcx/OSL+gs=
      - key: RATE_LIMIT
        value: "10"
      - key: CORS_ORIGINS
        value: "http://localhost:5173,https://lego-gpt.onrender.com"

  - type: web
    name: lego-gpt-api-blue
    runtime: python
    rootDir: .
    buildCommand: pip install -e backend
    startCommand: uvicorn backend.api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: false
    branch: main
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: REDIS_URL
        fromService:
          type: redis
          name: lego-gpt-redis
          property: connectionString
      - key: JWT_SECRET
        value: ycQGGSqO3/JYGY96TLnC829sXFPHMW+OFIcx/OSL+gs=
      - key: RATE_LIMIT
        value: "10"
      - key: CORS_ORIGINS
        value: "http://localhost:5173,https://lego-gpt.onrender.com"

  - type: redis
    name: lego-gpt-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: lego-gpt
    runtime: static
    rootDir: frontend
    buildCommand: |
      pnpm install --no-frozen-lockfile
      pnpm run build
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_URL
        value: "https://lego-gpt-api-green.onrender.com"
    staticPublishPath: dist
    branch: main
    autoDeploy: true
