version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app/backend
    volumes:
      - .:/app/backend
    ports:
      - "8000:8000"
    command: lego-gpt-server
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app/backend
    volumes:
      - .:/app/backend
    command: lego-gpt-worker
