version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: python server.py
