version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app/backend
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: poetry run uvicorn api:app --host 0.0.0.0 --port 8000 --reload
