[project]
name = "lego-gpt-backend"
version = "0.5.15"
requires-python = ">=3.11"
dependencies = [
    "redis>=5",
    "rq>=1.16",
    "ortools>=9.10",
]

[project.optional-dependencies]
test = [
    "fakeredis>=2.21",
]
cv = [
    "ultralytics>=8",
    "pillow>=10",
]
s3 = [
    "boto3>=1.34",
]

[project.scripts]
lego-gpt-server = "backend.server:main"
lego-gpt-worker = "backend.worker:main"
lego-detect-worker = "detector.worker:main"
lego-detect-train = "detector.train:main"

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"
