[project]
name = "lego-gpt-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "redis>=5",
    "rq>=1.16",
    "ortools>=9.10",
]

[project.optional-dependencies]
test = [
    "fakeredis>=2.21",
]
