[project]
name = "lego-gpt-backend"
version = "0.5.31"
requires-python = ">=3.11"
dependencies = [
    "redis>=5",
    "rq>=1.16",
    "ortools>=9.10",
]

[project.optional-dependencies]
test = [
    "fakeredis>=2.21",
    "ruff>=0.4",
]
cv = [
    "ultralytics>=8",
    "pillow>=10",
]
s3 = [
    "boto3>=1.34",
]
env = [
    "python-dotenv>=1",
]

[project.scripts]
lego-gpt-server = "backend.gateway:main"
lego-gpt-worker = "backend.worker:main"
lego-detect-worker = "detector.worker:main"
lego-detect-train = "detector.train:main"
lego-gpt-cli = "backend.cli:main"
lego-gpt-cleanup = "backend.cleanup:main"
lego-gpt-token = "backend.token_cli:main"
lego-gpt-export = "backend.export:main"

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"
