[project]
name = "lego-gpt-backend"
version = "0.5.1"
requires-python = ">=3.11"
dependencies = [
    "redis>=5",
    "rq>=1.16",
    "ortools>=9.10",
]

[project.optional-dependencies]
test = [
    "fakeredis>=2.21",
]
cv = [
    "ultralytics>=8",
    "pillow>=10",
]

[project.scripts]
lego-gpt-server = "backend.server:main"
lego-gpt-worker = "backend.worker:run_worker"
lego-detect-worker = "detector.worker:run_detector"
