apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: lego-gpt-api
spec:
  selector:
    app: lego-gpt-api
  ports:
    - port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: lego-gpt-metrics
spec:
  selector:
    app: lego-gpt-metrics
  ports:
    - port: 8777
