apiVersion: v1
kind: Secret
metadata:
  name: lego-gpt-secret
stringData:
  jwt-secret: change-me
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lego-gpt-api
spec:
  selector:
    matchLabels:
      app: lego-gpt-api
  template:
    metadata:
      labels:
        app: lego-gpt-api
    spec:
      containers:
        - name: api
          image: ghcr.io/<owner>/lego-gpt:v0.5.61
          env:
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lego-gpt-secret
                  key: jwt-secret
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: lego-gpt-api
spec:
  selector:
    app: lego-gpt-api
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lego-gpt-worker
spec:
  selector:
    matchLabels:
      app: lego-gpt-worker
  template:
    metadata:
      labels:
        app: lego-gpt-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/<owner>/lego-gpt:v0.5.61
          command: ["lego-gpt-worker"]
          env:
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lego-gpt-secret
                  key: jwt-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lego-detect-worker
spec:
  selector:
    matchLabels:
      app: lego-detect-worker
  template:
    metadata:
      labels:
        app: lego-detect-worker
    spec:
      containers:
        - name: detector
          image: ghcr.io/<owner>/lego-gpt:v0.5.61
          command: ["lego-detect-worker"]
          env:
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lego-gpt-secret
                  key: jwt-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lego-gpt-metrics
spec:
  selector:
    matchLabels:
      app: lego-gpt-metrics
  template:
    metadata:
      labels:
        app: lego-gpt-metrics
    spec:
      containers:
        - name: metrics
          image: ghcr.io/<owner>/lego-gpt:v0.5.61
          command: ["lego-gpt-metrics"]
          env:
            - name: REDIS_URL
              value: "redis://redis:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  name: lego-gpt-metrics
spec:
  selector:
    app: lego-gpt-metrics
  ports:
    - port: 8777
      targetPort: 8777
