name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff and coverage
        run: pip install ruff coverage

      - name: Run ruff
        run: ruff check backend detector

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -v
          coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.5.2

      - name: Install front-end dependencies
        run: pnpm install --no-frozen-lockfile --dir frontend

      - name: Run front-end lint
        run: pnpm --dir frontend run lint
      - name: Run scalability benchmark
        run: python scripts/benchmark_ci.py
      # 6. (Optional) Build dev Docker image
      # - name: Build Docker image
      #   run: docker build -f Dockerfile.dev -t lego-gpt-dev .

  scan-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -f backend/Dockerfile.cpu -t lego-gpt:test .
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: lego-gpt:test
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
