name: Dependency Audit

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install backend dependencies
        run: |
          python -m pip install --editable ./backend[env] pip-audit
      - name: Run pip-audit
        run: pip-audit
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v2
        with:
          version: 10.5.2
      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile --dir frontend
      - name: Run pnpm audit
        run: pnpm audit --dir frontend
