name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Bump version
        run: |
          tag=${GITHUB_REF#refs/tags/}
          python scripts/bump_version.py ${tag#v}
      - name: Commit version bump
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "chore: bump version to ${tag#v}"
          git push

  build-images:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push CPU image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile.cpu
          push: true
          tags: ghcr.io/${{ github.repository }}/lego-gpt:${{ github.ref_name }}
      - name: Build and push GPU image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile.gpu
          push: true
          tags: ghcr.io/${{ github.repository }}/lego-gpt:gpu-${{ github.ref_name }}
