name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Bump version
        run: |
          tag=${GITHUB_REF#refs/tags/}
          python scripts/bump_version.py ${tag#v}
      - name: Commit version bump
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "chore: bump version to ${tag#v}"
          git push
