name: Container Scan

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          scan-type: fs
          scan-ref: .
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: 1
